#Set the server port to 0 so that any random available port get assigned
server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka
    register-with-eureka: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
#Below entry for testing cache refresh    
emp: 
  name: Employee1
          
#Sleuth logging configuration        
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG